name: Node Continuous Integration

on: 
  pull_request:
    branches: [main]
  push:
    branches: [ "main" ]
    workflow_dispatch:

jobs: 
  test_pull_request:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-nod@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm test:ci
      - run: npm run build